@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb :pageTitle="$user ? __('Edit Pengguna') : __('Tambah Pengguna')" />
<form method="POST" action="{{ route('maklumat-login.save', ['id' => $user?->id]) }}" class="space-y-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">@csrf
    <div class="border-b border-gray-100 pb-5 dark:border-gray-800"><h2 class="text-lg font-semibold text-gray-800 dark:text-white/90">{{ __('Maklumat Akaun') }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ __('Lengkapkan maklumat login pengguna.') }}</p></div>
    <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
        @foreach (['name' => 'Nama Pengguna', 'no_kp' => 'No. Kad Pengenalan', 'email' => 'E-mel'] as $field => $label)<div class="{{ $field === 'email' ? 'md:col-span-2' : '' }}"><label for="{{ $field }}" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __($label) }}</label><input id="{{ $field }}" name="{{ $field }}" type="{{ $field === 'email' ? 'email' : 'text' }}" value="{{ old($field, $user?->$field) }}" required class="w-full min-h-11 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error($field)<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>@endforeach
        <div><label for="password" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Kata Laluan') }}{{ $user ? ' (kosongkan jika tidak berubah)' : '' }}</label><input id="password" name="password" type="password" {{ $user ? '' : 'required' }} minlength="8" class="w-full min-h-11 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('password')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
        <div><label for="password_confirmation" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Sahkan Kata Laluan') }}</label><input id="password_confirmation" name="password_confirmation" type="password" minlength="8" class="w-full min-h-11 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
    </div>
    <div class="flex justify-end gap-3 border-t border-gray-100 pt-5 dark:border-gray-800"><a href="{{ route('maklumat-login') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 dark:border-gray-700 dark:text-gray-300">{{ __('Kembali') }}</a><button class="rounded-lg bg-brand-500 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-brand-600">{{ __('Simpan Pengguna') }}</button></div>
</form>
@endsection
