@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb :pageTitle="$lo ? __('Kemaskini LO') : __('Tambah LO')" />

    <form method="POST" enctype="multipart/form-data" action="{{ $lo ? route('lo.update', $lo->lo_inden_id) : route('lo.store') }}" class="space-y-6 font-outfit">
        @csrf
        @if($lo) @method('PUT') @endif
        <div class="flex justify-end"><a href="{{ $lo ? route('lo.show', $lo->lo_inden_id) : route('lo') }}" class="inline-flex h-11 items-center justify-center rounded-lg border border-gray-300 bg-white px-4 text-sm font-medium text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 dark:hover:bg-gray-800">{{ __('Kembali') }}</a></div>

        <x-common.document-card :title="$lo ? __('Maklumat LO') : __('Maklumat LO Baharu')">
            <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
                <div><label for="lo_inden_no" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('No. LO') }} <span class="text-error-500">*</span></label><input id="lo_inden_no" name="lo_inden_no" value="{{ old('lo_inden_no', $lo->lo_inden_no ?? '') }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('lo_inden_no')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="customer_id" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Pelanggan / Syarikat') }} <span class="text-error-500">*</span></label><select id="customer_id" name="customer_id" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">{{ __('Pilih pelanggan') }}</option>@foreach($customers as $customer)<option value="{{ $customer->customer_id }}" @selected((string) old('customer_id', $lo->customer_id ?? '') === (string) $customer->customer_id)>{{ $customer->company_name ?: $customer->customer_name }}</option>@endforeach</select>@error('customer_id')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="lo_inden_date" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Tarikh LO') }} <span class="text-error-500">*</span></label><input id="lo_inden_date" name="lo_inden_date" type="date" value="{{ old('lo_inden_date', isset($lo) ? \Carbon\Carbon::parse($lo->lo_inden_date)->format('Y-m-d') : now()->format('Y-m-d')) }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('lo_inden_date')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="amount" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Jumlah (RM)') }} <span class="text-error-500">*</span></label><input id="amount" name="amount" type="number" min="0" step="0.01" value="{{ old('amount', $lo->amount ?? '0.00') }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('amount')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div class="md:col-span-2" x-data="{ fileName: '' }">
                    <label for="document_file" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Dokumen LO') }} @if(! $lo)<span class="text-error-500">*</span>@endif</label>
                    <input id="document_file" name="document_file" type="file" accept="application/pdf,image/jpeg,image/png" @if(! $lo) required @endif class="sr-only" @change="fileName = $event.target.files[0]?.name || ''">
                    <label for="document_file" class="flex cursor-pointer flex-col gap-3 rounded-xl border border-dashed border-gray-300 bg-gray-50 p-4 transition hover:border-brand-400 hover:bg-brand-50/40 dark:border-gray-700 dark:bg-gray-900/40 dark:hover:border-brand-500 dark:hover:bg-brand-500/5 sm:flex-row sm:items-center sm:justify-between">
                        <span class="flex min-w-0 items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-400"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 16V4m0 0-4 4m4-4 4 4M5 14v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4"/></svg></span><span class="min-w-0"><span class="block text-sm font-medium text-gray-800 dark:text-white/90" x-text="fileName || '{{ __('Pilih fail PDF atau imej') }}'"></span><span class="mt-0.5 block truncate text-xs text-gray-500 dark:text-gray-400" x-text="fileName ? '{{ __('Fail telah dipilih') }}' : '{{ __('PDF, JPG, JPEG atau PNG · Maksimum 10MB') }}'"></span></span></span>
                        <span class="inline-flex shrink-0 items-center justify-center rounded-lg bg-brand-500 px-3 py-2 text-sm font-medium text-white">{{ __('Pilih Fail') }}</span>
                    </label>
                    @if($lo?->document_file)<a href="{{ route('lo.document', $lo->lo_inden_id) }}" target="_blank" rel="noopener" class="mt-3 inline-flex text-sm font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">{{ __('Lihat dokumen semasa') }}</a>@endif
                    @error('document_file')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror
                </div>
            </div>
        </x-common.document-card>
        <div class="flex justify-end"><button type="submit" class="inline-flex h-11 items-center justify-center rounded-lg bg-brand-500 px-5 text-sm font-medium text-white transition hover:bg-brand-600">{{ $lo ? __('Simpan Kemaskini') : __('Simpan LO') }}</button></div>
    </form>
@endsection
