@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb :pageTitle="$lo ? __('Kemaskini LO') : __('Tambah LO')" />

    <form method="POST" enctype="multipart/form-data" action="{{ $lo ? route('lo.update', $lo->lo_inden_id) : route('lo.store') }}" class="space-y-6 font-outfit">
        @csrf
        @if($lo) @method('PUT') @endif
        <div class="flex justify-end"><a href="{{ $lo ? route('lo.show', $lo->lo_inden_id) : route('lo') }}" class="inline-flex h-11 items-center justify-center rounded-lg border border-gray-300 bg-white px-4 text-sm font-medium text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 dark:hover:bg-gray-800">{{ __('Kembali') }}</a></div>

        <x-common.document-card :title="$lo ? __('Maklumat LO') : __('Maklumat LO Baharu')">
            <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
                <div><label for="lo_inden_no" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('No. LO') }} <span class="text-error-500">*</span></label><input id="lo_inden_no" name="lo_inden_no" value="{{ old('lo_inden_no', $lo->lo_inden_no ?? '') }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('lo_inden_no')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="customer_id" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Pelanggan / Syarikat') }} <span class="text-error-500">*</span></label><select id="customer_id" name="customer_id" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">{{ __('Pilih pelanggan') }}</option>@foreach($customers as $customer)<option value="{{ $customer->customer_id }}" @selected((string) old('customer_id', $lo->customer_id ?? '') === (string) $customer->customer_id)>{{ $customer->company_name ?: $customer->customer_name }}</option>@endforeach</select>@error('customer_id')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="lo_inden_date" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Tarikh LO') }} <span class="text-error-500">*</span></label><input id="lo_inden_date" name="lo_inden_date" type="date" value="{{ old('lo_inden_date', isset($lo) ? \Carbon\Carbon::parse($lo->lo_inden_date)->format('Y-m-d') : now()->format('Y-m-d')) }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('lo_inden_date')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div><label for="amount" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Jumlah (RM)') }} <span class="text-error-500">*</span></label><input id="amount" name="amount" type="number" min="0" step="0.01" value="{{ old('amount', $lo->amount ?? '0.00') }}" required class="min-h-11 w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('amount')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
                <div class="md:col-span-2"><label for="document_file" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Dokumen LO') }} @if(! $lo)<span class="text-error-500">*</span>@endif</label><input id="document_file" name="document_file" type="file" accept="application/pdf,image/jpeg,image/png" @if(! $lo) required @endif class="block w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm text-gray-700 file:me-4 file:border-0 file:bg-brand-50 file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-brand-600 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 dark:file:bg-brand-500/10 dark:file:text-brand-400"><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">{{ __('Format: PDF, JPG, JPEG atau PNG. Maksimum 10MB.') }}</p>@if($lo?->document_file)<a href="{{ route('lo.document', $lo->lo_inden_id) }}" target="_blank" rel="noopener" class="mt-2 inline-flex text-sm font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">{{ __('Lihat dokumen semasa') }}</a>@endif @error('document_file')<p class="mt-1 text-sm text-error-600">{{ $message }}</p>@enderror</div>
            </div>
        </x-common.document-card>
        <div class="flex justify-end"><button type="submit" class="inline-flex h-11 items-center justify-center rounded-lg bg-brand-500 px-5 text-sm font-medium text-white transition hover:bg-brand-600">{{ $lo ? __('Simpan Kemaskini') : __('Simpan LO') }}</button></div>
    </form>
@endsection
