@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb :pageTitle="$quotation ? __('Edit Sebut Harga Pembekal') : __('Tambah Sebut Harga Pembekal')" />
@php($initialItems = $items->isNotEmpty() ? $items->map(fn ($item, $index) => ['id' => $index + 1, 'description' => $item->item_description, 'quantity' => $item->quantity, 'unit' => $item->unit, 'price' => $item->unit_price])->values() : collect([['id' => 1, 'description' => '', 'quantity' => 1, 'unit' => '', 'price' => 0]]))
<form method="POST" enctype="multipart/form-data" action="{{ route('sebut-harga-pembekal.save', ['id' => $quotation?->supplier_quotation_id]) }}" class="space-y-6" x-data="{ items: @js($initialItems), nextId: {{ $initialItems->count() + 1 }}, addItem() { this.items.push({ id: this.nextId++, description: '', quantity: 1, unit: '', price: 0 }) }, subtotal(item) { return (Number(item.quantity) || 0) * (Number(item.price) || 0) }, get total() { return this.items.reduce((sum, item) => sum + this.subtotal(item), 0) } }">
    @csrf
    <x-common.document-card :title="__('Maklumat Sebut Harga Pembekal')">
        <div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <div><label for="supplier_id" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Nama Syarikat') }}</label><select id="supplier_id" name="supplier_id" required class="w-full min-h-11 rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">{{ __('Pilih pembekal') }}</option>@foreach ($suppliers as $supplier)<option value="{{ $supplier->customer_id }}" @selected(old('supplier_id', $quotation?->supplier_id) == $supplier->customer_id)>{{ $supplier->company_name }}</option>@endforeach</select></div>
            <div><label for="quotation_no_supplier" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('No. Sebut Harga Pembekal') }}</label><input id="quotation_no_supplier" name="quotation_no_supplier" required value="{{ old('quotation_no_supplier', $quotation?->quotation_no_supplier) }}" class="w-full min-h-11 rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label for="quotation_title" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Tajuk Sebut Harga') }}</label><input id="quotation_title" name="quotation_title" value="{{ old('quotation_title', $quotation?->quotation_title) }}" class="w-full min-h-11 rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label for="person_in_charge" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Person In Charge') }}</label><input id="person_in_charge" name="person_in_charge" value="{{ old('person_in_charge', $quotation?->person_in_charge) }}" class="w-full min-h-11 rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div class="sm:col-span-2"><label for="supplier_quotation_file" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">{{ __('Upload Sebut Harga (PDF)') }}</label><input id="supplier_quotation_file" name="supplier_quotation_file" type="file" accept="application/pdf" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@if ($quotation?->file_name)<p class="mt-2 text-sm text-gray-500 dark:text-gray-400">{{ __('Fail semasa') }}: {{ $quotation->file_name }}</p>@endif</div>
        </div>
    </x-common.document-card>
    <x-common.document-card :title="__('Item Sebut Harga')">
        <div class="overflow-x-auto"><table class="w-full min-w-[900px]"><thead><tr class="bg-error-800 text-white">@foreach (['Bil.', 'Perihal Barangan', 'Kuantiti', 'Unit', 'Harga Seunit (RM)', 'Jumlah (RM)', 'Tindakan'] as $heading)<th class="px-3 py-3 text-start text-theme-xs">{{ __($heading) }}</th>@endforeach</tr></thead><tbody><template x-for="(item, index) in items" :key="item.id"><tr class="border-b border-gray-100 dark:border-gray-800"><td class="p-3 text-center" x-text="index + 1"></td><td class="min-w-60 p-3"><textarea :name="`items[${index}][description]`" x-model="item.description" rows="2" required class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></textarea></td><td class="min-w-28 p-3"><input :name="`items[${index}][quantity]`" x-model.number="item.quantity" type="number" min="0.01" step="0.01" required class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></td><td class="min-w-28 p-3"><input :name="`items[${index}][unit]`" x-model="item.unit" required class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></td><td class="min-w-36 p-3"><input :name="`items[${index}][price]`" x-model.number="item.price" type="number" min="0" step="0.01" required class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></td><td class="p-3" x-text="subtotal(item).toFixed(2)"></td><td class="p-3"><button type="button" @click="items.splice(index, 1)" :disabled="items.length === 1" class="text-error-600 disabled:opacity-40">{{ __('Buang') }}</button></td></tr></template></tbody></table></div><button type="button" @click="addItem()" class="mt-4 rounded-lg border border-brand-300 px-4 py-2 text-sm font-medium text-brand-600">+ {{ __('Tambah Item') }}</button><div class="mt-4 text-end text-lg font-semibold">{{ __('Jumlah Total') }}: RM <span x-text="total.toFixed(2)"></span></div>
    </x-common.document-card>
    <div class="flex justify-end gap-3"><a href="{{ route('sebut-harga-pembekal') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:text-gray-300">{{ __('Kembali') }}</a><button class="rounded-lg bg-brand-500 px-5 py-2.5 text-sm font-medium text-white">{{ __('Simpan') }}</button></div>
</form>
@endsection
